const S = require("fluent-json-schema");
const classes = require("../../../enums/classes");

module.exports = (S.object()
	.id("completeDetails")
	.additionalProperties(false)
	.prop("bossId", S.number().required())
	.prop("areaId", S.number().required())
	.prop("fightDuration", S.string().required())
	.prop("partyDps", S.string().required())
	.prop("debuffUptime", S.array().items(
		S.object()
			.additionalProperties(false)
			.prop("key", S.number().required())
			.prop("value", S.number().required())
	))
	.prop("uploader", S.object()
		.additionalProperties(false)
		.prop("playerClass", S.enum(Object.values(classes)).required())
		.prop("playerName", S.string().required())
		.prop("playerId", S.number().required())
		.prop("playerServerId", S.number().required())
	)
	.prop("members", S.array().items(
		S.object()
			.prop("playerClass", S.enum(Object.values(classes)).required())
			.prop("playerName", S.string().required())
			.prop("playerId", S.number().required())
			.prop("playerServerId", S.number().required())
			.prop("aggroPercent", S.number().required())
			.prop("playerAverageCritRate", S.number().required())
			.prop("playerDeathDuration", S.string().required())
			.prop("playerDeaths", S.number().required())
			.prop("playerDps", S.string().required())
			.prop("playerTotalDamage", S.string().required())
			.prop("playerTotalDamagePercentage", S.number().required())
			.prop("buffUptime", S.array().items(
				S.object()
					.additionalProperties(false)
					.prop("key", S.number().required())
					.prop("value", S.number().required())
			))
			.prop("skillLog", S.array().items(
				S.object()
					.additionalProperties(false)
					.prop("skillAverageCrit", S.string().required())
					.prop("skillAverageWhite", S.string().required())
					.prop("skillCritRate", S.number().required())
					.prop("skillDamagePercent", S.number().required())
					.prop("skillHighestCrit", S.string().required())
					.prop("skillHits", S.string().required())
					.prop("skillCasts", S.string().required())
					.prop("skillId", S.number().required())
					.prop("skillLowestCrit", S.string().required())
					.prop("skillTotalDamage", S.string().required())
			))
	))
)
	.valueOf();